/**
 * @typedef {Object} HTML
 * @property {new () => HTMLAnchorElement} A
 * @property {new () => HTMLElement} Abbr
 * @property {new () => HTMLElement} Address
 * @property {new () => HTMLAreaElement} Area
 * @property {new () => HTMLElement} Article
 * @property {new () => HTMLElement} Aside
 * @property {new () => HTMLAudioElement} Audio
 * @property {new () => HTMLElement} B
 * @property {new () => HTMLBaseElement} Base
 * @property {new () => HTMLElement} Bdi
 * @property {new () => HTMLElement} Bdo
 * @property {new () => HTMLQuoteElement} BlockQuote
 * @property {new () => HTMLBodyElement} Body
 * @property {new () => HTMLBRElement} BR
 * @property {new () => HTMLButtonElement} Button
 * @property {new () => HTMLCanvasElement} Canvas
 * @property {new () => HTMLTableCaptionElement} Caption
 * @property {new () => HTMLElement} Cite
 * @property {new () => HTMLElement} Code
 * @property {new () => HTMLTableColElement} Col
 * @property {new () => HTMLTableColElement} ColGroup
 * @property {new () => HTMLDataElement} Data
 * @property {new () => HTMLDataListElement} DataList
 * @property {new () => HTMLElement} DD
 * @property {new () => HTMLModElement} Del
 * @property {new () => HTMLDetailsElement} Details
 * @property {new () => HTMLElement} Dfn
 * @property {new () => HTMLDialogElement} Dialog
 * @property {new () => HTMLDivElement} Div
 * @property {new () => HTMLDListElement} DL
 * @property {new () => HTMLElement} DT
 * @property {new () => HTMLElement} Em
 * @property {new () => HTMLEmbedElement} Embed
 * @property {new () => HTMLFieldSetElement} FieldSet
 * @property {new () => HTMLElement} FigCaption
 * @property {new () => HTMLElement} Figure
 * @property {new () => HTMLElement} Footer
 * @property {new () => HTMLFormElement} Form
 * @property {new () => HTMLHeadingElement} H1
 * @property {new () => HTMLHeadingElement} H2
 * @property {new () => HTMLHeadingElement} H3
 * @property {new () => HTMLHeadingElement} H4
 * @property {new () => HTMLHeadingElement} H5
 * @property {new () => HTMLHeadingElement} H6
 * @property {new () => HTMLHeadElement} Head
 * @property {new () => HTMLElement} Header
 * @property {new () => HTMLHRElement} HR
 * @property {new () => HTMLHtmlElement} Html
 * @property {new () => HTMLElement} I
 * @property {new () => HTMLIFrameElement} IFrame
 * @property {new () => HTMLImageElement} Img
 * @property {new () => HTMLInputElement} Input
 * @property {new () => HTMLModElement} Ins
 * @property {new () => HTMLElement} Kbd
 * @property {new () => HTMLLabelElement} Label
 * @property {new () => HTMLLegendElement} Legend
 * @property {new () => HTMLLIElement} LI
 * @property {new () => HTMLLinkElement} Link
 * @property {new () => HTMLElement} Main
 * @property {new () => HTMLMapElement} Map
 * @property {new () => HTMLElement} Mark
 * @property {new () => HTMLMenuElement} Menu
 * @property {new () => HTMLMetaElement} Meta
 * @property {new () => HTMLMeterElement} Meter
 * @property {new () => HTMLElement} Nav
 * @property {new () => HTMLElement} NoScript
 * @property {new () => HTMLObjectElement} Object
 * @property {new () => HTMLOListElement} OL
 * @property {new () => HTMLOptGroupElement} OptGroup
 * @property {new () => HTMLOptionElement} Option
 * @property {new () => HTMLOutputElement} Output
 * @property {new () => HTMLParagraphElement} P
 * @property {new () => HTMLPictureElement} Picture
 * @property {new () => HTMLUnknownElement} Portal
 * @property {new () => HTMLPreElement} Pre
 * @property {new () => HTMLProgressElement} Progress
 * @property {new () => HTMLQuoteElement} Q
 * @property {new () => HTMLElement} RP
 * @property {new () => HTMLElement} RT
 * @property {new () => HTMLElement} Ruby
 * @property {new () => HTMLElement} S
 * @property {new () => HTMLElement} Samp
 * @property {new () => HTMLScriptElement} Script
 * @property {new () => HTMLElement} Section
 * @property {new () => HTMLSelectElement} Select
 * @property {new () => HTMLSlotElement} Slot
 * @property {new () => HTMLElement} Small
 * @property {new () => HTMLSourceElement} Source
 * @property {new () => HTMLSpanElement} Span
 * @property {new () => HTMLElement} Strong
 * @property {new () => HTMLStyleElement} Style
 * @property {new () => HTMLElement} Sub
 * @property {new () => HTMLElement} Summary
 * @property {new () => HTMLElement} Sup
 * @property {new () => HTMLTableElement} Table
 * @property {new () => HTMLTableSectionElement} TBody
 * @property {new () => HTMLTableCellElement} TD
 * @property {new () => HTMLTemplateElement} Template
 * @property {new () => HTMLTextAreaElement} TextArea
 * @property {new () => HTMLTableSectionElement} TFoot
 * @property {new () => HTMLTableCellElement} TH
 * @property {new () => HTMLTableSectionElement} THead
 * @property {new () => HTMLTimeElement} Time
 * @property {new () => HTMLTitleElement} Title
 * @property {new () => HTMLTableRowElement} TR
 * @property {new () => HTMLTrackElement} Track
 * @property {new () => HTMLElement} U
 * @property {new () => HTMLUListElement} UL
 * @property {new () => HTMLElement} Var
 * @property {new () => HTMLVideoElement} Video
 * @property {new () => HTMLElement} Wbr
 */
/**
 * Given an optional global context, returns a proxy that resolves
 * all tag names into their global constructors.
 * @property {globalThis} [self=globalThis]
 * @returns {HTML}
 */
export default function _default(self?: typeof globalThis): HTML;
export type HTML = {
    A: new () => HTMLAnchorElement;
    Abbr: new () => HTMLElement;
    Address: new () => HTMLElement;
    Area: new () => HTMLAreaElement;
    Article: new () => HTMLElement;
    Aside: new () => HTMLElement;
    Audio: new () => HTMLAudioElement;
    B: new () => HTMLElement;
    Base: new () => HTMLBaseElement;
    Bdi: new () => HTMLElement;
    Bdo: new () => HTMLElement;
    BlockQuote: new () => HTMLQuoteElement;
    Body: new () => HTMLBodyElement;
    BR: new () => HTMLBRElement;
    Button: new () => HTMLButtonElement;
    Canvas: new () => HTMLCanvasElement;
    Caption: new () => HTMLTableCaptionElement;
    Cite: new () => HTMLElement;
    Code: new () => HTMLElement;
    Col: new () => HTMLTableColElement;
    ColGroup: new () => HTMLTableColElement;
    Data: new () => HTMLDataElement;
    DataList: new () => HTMLDataListElement;
    DD: new () => HTMLElement;
    Del: new () => HTMLModElement;
    Details: new () => HTMLDetailsElement;
    Dfn: new () => HTMLElement;
    Dialog: new () => HTMLDialogElement;
    Div: new () => HTMLDivElement;
    DL: new () => HTMLDListElement;
    DT: new () => HTMLElement;
    Em: new () => HTMLElement;
    Embed: new () => HTMLEmbedElement;
    FieldSet: new () => HTMLFieldSetElement;
    FigCaption: new () => HTMLElement;
    Figure: new () => HTMLElement;
    Footer: new () => HTMLElement;
    Form: new () => HTMLFormElement;
    H1: new () => HTMLHeadingElement;
    H2: new () => HTMLHeadingElement;
    H3: new () => HTMLHeadingElement;
    H4: new () => HTMLHeadingElement;
    H5: new () => HTMLHeadingElement;
    H6: new () => HTMLHeadingElement;
    Head: new () => HTMLHeadElement;
    Header: new () => HTMLElement;
    HR: new () => HTMLHRElement;
    Html: new () => HTMLHtmlElement;
    I: new () => HTMLElement;
    IFrame: new () => HTMLIFrameElement;
    Img: new () => HTMLImageElement;
    Input: new () => HTMLInputElement;
    Ins: new () => HTMLModElement;
    Kbd: new () => HTMLElement;
    Label: new () => HTMLLabelElement;
    Legend: new () => HTMLLegendElement;
    LI: new () => HTMLLIElement;
    Link: new () => HTMLLinkElement;
    Main: new () => HTMLElement;
    Map: new () => HTMLMapElement;
    Mark: new () => HTMLElement;
    Menu: new () => HTMLMenuElement;
    Meta: new () => HTMLMetaElement;
    Meter: new () => HTMLMeterElement;
    Nav: new () => HTMLElement;
    NoScript: new () => HTMLElement;
    Object: new () => HTMLObjectElement;
    OL: new () => HTMLOListElement;
    OptGroup: new () => HTMLOptGroupElement;
    Option: new () => HTMLOptionElement;
    Output: new () => HTMLOutputElement;
    P: new () => HTMLParagraphElement;
    Picture: new () => HTMLPictureElement;
    Portal: new () => HTMLUnknownElement;
    Pre: new () => HTMLPreElement;
    Progress: new () => HTMLProgressElement;
    Q: new () => HTMLQuoteElement;
    RP: new () => HTMLElement;
    RT: new () => HTMLElement;
    Ruby: new () => HTMLElement;
    S: new () => HTMLElement;
    Samp: new () => HTMLElement;
    Script: new () => HTMLScriptElement;
    Section: new () => HTMLElement;
    Select: new () => HTMLSelectElement;
    Slot: new () => HTMLSlotElement;
    Small: new () => HTMLElement;
    Source: new () => HTMLSourceElement;
    Span: new () => HTMLSpanElement;
    Strong: new () => HTMLElement;
    Style: new () => HTMLStyleElement;
    Sub: new () => HTMLElement;
    Summary: new () => HTMLElement;
    Sup: new () => HTMLElement;
    Table: new () => HTMLTableElement;
    TBody: new () => HTMLTableSectionElement;
    TD: new () => HTMLTableCellElement;
    Template: new () => HTMLTemplateElement;
    TextArea: new () => HTMLTextAreaElement;
    TFoot: new () => HTMLTableSectionElement;
    TH: new () => HTMLTableCellElement;
    THead: new () => HTMLTableSectionElement;
    Time: new () => HTMLTimeElement;
    Title: new () => HTMLTitleElement;
    TR: new () => HTMLTableRowElement;
    Track: new () => HTMLTrackElement;
    U: new () => HTMLElement;
    UL: new () => HTMLUListElement;
    Var: new () => HTMLElement;
    Video: new () => HTMLVideoElement;
    Wbr: new () => HTMLElement;
};
